config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get "home/index"
  get "chat_rooms/index"
  get "chat_rooms/new"
  get "chat_rooms/create"

  get "home/index"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :chat_rooms, only: [:new, :create, :show, :index]
  root "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: chat_rooms
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_chat_rooms_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: messages
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  chat_room_id :bigint           not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_messages_on_chat_room_id  (chat_room_id)
#  index_messages_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (chat_room_id => chat_rooms.id)
#  fk_rails_...  (user_id => users.id)
#
class Message < ApplicationRecord
  has_rich_text :body
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime("%H:%M:%S %d %B %Y")
  end
end

app/models/user.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  avatar_fb              :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  uid                    :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  include Users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :omniauthable, omniauth_providers: [:facebook]

  has_one_attached :avatar, dependent: :destroy

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :email, presence: true
  validates :username,  length: { in: 3..10 },
                        uniqueness: true,
                        if: -> { username.present? }

  def name
    username || email.split("@")[0]
  end

  def avatar?
    avatar.attached? || avatar_fb.present?
  end

  def final_avatar
    return avatar if avatar.attached?
    return avatar_fb if avatar_fb.present?
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session["devise.facebook_data"]) &&
         (session["devise.facebook_data"]["extra"]["raw_info"] && user.email.blank?)
        user.email = data["email"]
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name
      user.avatar_fb = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_chat_rooms
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_chat_rooms
    @chat_rooms = ChatRoom.all
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/chat_rooms_controller.rb
# frozen_string_literal: true
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = "Chat room added!"
      redirect_to(chat_rooms_path)
    else
      render("new")
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  def index; end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true
class MessagesController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :facebook

    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect(@user, event: :authentication)
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra)
        redirect_to(new_user_registration_url)
      end
    end

    def failure
      redirect_to(root_path)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag("https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
      opts)
  end
end

app/helpers/chat_rooms_helper.rb
# frozen_string_literal: true
module ChatRoomsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true
module HomeHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true
module MessagesHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to t("chat_room.enter", chat_room_name: chat_room.title), chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to t("chat_room.new"), new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1><%= t("chat_room.add") %></h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<%= form_for @message, url: "#", remote: true do |f| %>
  <div class="form-group">
    <%= f.rich_text_area :body, class: 'form-control' %>
    <small class="text-muted"><%= t("chat_room.body_limit", min: 2, max: 1000) %></small>
  </div>

  <%= f.submit t("chat_room.send"), class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bchat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
      <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
      </symbol>
      <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>

    <%= render partial: "layouts/shared/navbar" %>

    <div class="container-fluid">
      <div class="row flex-nowrap">
        <% if user_signed_in? %>
          <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <%= render partial: "layouts/shared/sidebar" %>
          </div>
        <% end %>
        <div class="col py-3">
          <%= render partial: "layouts/shared/alerts_notices" %>
          <%= yield %>
        </div>
      </div>
    </body>
  </html>

app/views/layouts/shared/_alerts_notices.html.erb
<% if notice %>
  <div class="row">
    <div class="col">
      <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <div>
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="row">
    <div class="col">
      <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Bchat", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">

            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= render partial: "shared/avatar", locals: {user: current_user, css_classes: "avatar"} %>
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "Perfil", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_sidebar.html.erb
<div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
  <a href="<%= new_chat_room_path %>" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <span class="fs-5 d-none d-sm-inline"><%= t("chat_room.new") %></span>
    <i class="fa fa-plus-circle ms-3" aria-hidden="true"></i>
  </a>
  <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
    <%= @chat_rooms.find_each do |chat_room| %>
      <li class="nav-item">
        <a href="<%= chat_room_path(chat_room) %>" class="nav-link align-middle px-0">
          <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline"><%= chat_room.title %></span>
        </a>
      </li>
    <% end %>

  </ul>
</div>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= render partial: "shared/avatar", locals: {user: message.user, css_classes: "avatar"} %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= t("message.text", name: message.user.name, time: l(message.created_at)) %></span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_avatar.html.erb
<% if user.avatar? %>
  <%= image_tag user.final_avatar, class: css_classes %>
<% else %>
  <%= image_tag "fallback/default_avatar.png", class: css_classes %>
<% end %>